version: '3.3'

services:
  mongodb:
    image: mongo:latest
    container_name: kalah_mongodb
    ports:
      - 27017:27017
  kalah-api:
    build: ../service
    container_name: kalah_api
    depends_on:
      - mongodb
    ports:
      - 8090:8080
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017
